nohup: ignoring input
W0327 07:44:39.321352 139671418738496 torch/distributed/run.py:779] 
W0327 07:44:39.321352 139671418738496 torch/distributed/run.py:779] *****************************************
W0327 07:44:39.321352 139671418738496 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0327 07:44:39.321352 139671418738496 torch/distributed/run.py:779] *****************************************
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/monai/networks/nets/resnet.py:658: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(pretrained_path, map_location=torch.device(device))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/monai/networks/nets/resnet.py:658: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(pretrained_path, map_location=torch.device(device))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/data/ZZ_githubRepos/baselinesLungAmbition/ImageModels/ResNet/ResNet3D/model/metrics.py:20: RuntimeWarning: invalid value encountered in scalar divide
  test_NPV=tn/(tn+fn)
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/monai/networks/nets/resnet.py:658: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(pretrained_path, map_location=torch.device(device))
/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/monai/networks/nets/resnet.py:658: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(pretrained_path, map_location=torch.device(device))
[rank1]: [rank1]: Traceback (most recent call last):
[rank1]: [rank1]:   File "mainBMY0_pretrained.py", line 176, in <module>
[rank1]: [rank1]:     model = DDP(model, device_ids=[rank])
[rank1]: [rank1]:   File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 822, in __init__
[rank1]: [rank1]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank1]: [rank1]:   File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/utils.py", line 286, in _verify_param_shape_across_processes
[rank1]: [rank1]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank1]: [rank1]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:275, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.20.5
[rank1]: [rank1]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
[rank1]: [rank1]: Last error:
[rank1]: [rank1]: socketStartConnect: Connect to 172.16.5.82<40121> failed : Software caused connection abort
W0327 13:38:35.722028 139671418738496 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 922561 closing signal SIGTERM
E0327 13:38:36.038088 139671418738496 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 922562) of binary: /home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/bin/python3.8
Traceback (most recent call last):
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/tenerife/mambaforge/envs/lungAmbpy3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mainBMY0_pretrained.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-27_13:38:35
  host      : medicine-radiomics
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 922562)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
